#include<stdio.h>
int great(int a,int b,int c,int d)
{
    if(a>b)
    {
        if(a>c)
        {
            if(a>d)
            {
                printf("%d",a);
            }
        }
    }
    if(b>a)
    {
        if(b>c)
           {
               if(b>d)
               {
                   printf("%d",b);
               }
           }
    }
       if(c>a)
    {
        if(c>b)
           {
               if(c>d)
               {
                   printf("%d",c);
               }
           }
    }
    if(d>a)
    {
        if(d>b)
           {
               if(d>c)
               {
                   printf("%d",d);
               }
           }
    }
    return 0;
}
int main()
{
    int a,b,c,d;
    scanf("%d\n%d\n%d\n%d",&a,&b,&c,&d);
    great(a,b,c,d);
}